# docker-compose.yml
version: "3"

services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    master:
        build: ./master
        ports:
            - "80:80"
        environment:
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - redis

    worker:
        build: ./worker
        environment:
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - redis
        deploy:
            replicas: 4
